os:
  - osx

osx_image: xcode11.2  # This specifies the version of Xcode and macOS to run the build on

language: shell

install:
  - pip3 install pyinstaller Pillow

script:
  - pyinstaller --windowed --onefile main.py -n TicTacToe -p lib --add-data data/sprites:data/sprites -i data/sprites/Red_x.png
  - ls dist
  - git add dist/
  - git commit "New MacOS app released!"
  - git push

deploy:
  provider: releases
  token: $GH_TOKEN
  file: dist/TicTacToe.app
  cleanup: false
  on:
    all_branches: true
