os:
  - osx

osx_image: xcode11.2  # This specifies the version of Xcode and macOS to run the build on

language: shell

install:
  - pip3 install pyinstaller Pillow

script:
  - pyinstaller --windowed --onefile main.py -n TicTacToe -p lib --add-data data/sprites:data/sprites -i data/sprites/Red_x.png
  - ls dist
  - git checkout master
  - git add dist/
  - git commit -m "New MacOS app released!"

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name Dj-Frixz
  - git config --local user.email gmsccntdenmark@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: $GH_TOKEN
  file: dist/
  cleanup: false
