os:
  - osx

osx_image: xcode11.2  # This specifies the version of Xcode and macOS to run the build on

language: shell

install:
  - pip3 install pyinstaller

script:
  - pyinstaller --windowed main.py -n TicTacToe -d lib --add-data data/sprites:data/sprites -i data/sprites/Red_x.png

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/TicTacToe
  skip_cleanup: true
  on:
    tags: true
